backend/urls.py
from django.urls import path
from . import views

app_name = 'backend'
urlpatterns = [
    path('home/', views.home, name ='home'),
    path('', views.index, name ='index'),
    #path('students/', views.Students, name = 'students'),
    path('registration/', views.register_request, name='registration'),
    path('login/', views.login_request, name='login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.logout_request, name='logout'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('courses/', views.courses, name='courses'),
    path('update/', views.update, name='update'),
    path('inbox/', views.inbox, name='inbox'),
    path('settings/', views.settings, name='settings'),
    
    #FOR PASSWORD RESETTING OR LET'S SAY FORGOT PASSWORD

    path('password_reset/', views.CustomPasswordResetView.as_view(),  name='password_reset'),
    path('password_reset_done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

] 

skillup/urls.py
from django.contrib import admin
from django.urls import path, include

#to serve images and profile pics
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),      
    path('', include("backend.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from PIL import Image

# Create your models here.


class UserProfile(models.Model):
    Male = "M"
    Female = "F"

    gender = [
        (Male,"M"),
        (Female,"F"),
    ]


    
    AB='Abia'
    AD='Adamawa'
    AI='Akwa Ibom'
    AN='Anambra'
    BU='Bauchi'
    BY='Bayelsa'
    BN='Benue'
    BO='Borno'
    CR='Cross River'
    DL='Delta'
    EB='Ebonyi'
    ED='Edo'
    EK='Ekiti'
    EN='Enugu'
    GO='Gombe'
    IM='Imo'
    JI='Jigawa'
    KD='Kaduna'
    KN='Kano'
    KT='Katsina'
    KB='Kebbi'
    KG='Kogi'
    KW='Kwara'
    LG='Lagos'
    NS='Nasarawa'
    NG='Niger'
    OG='Ogun'
    ON='Ondo'
    OS='Osun'
    OY='Oyo'
    PL='Plateau'
    RS='Rivers'
    SK='Sokoto'
    TR='Taraba'
    YB='Yobe'
    ZM='Zamfara'


    state=[
            (AB,'Abia'),
            (AD,'Adamawa'),
            (AI,'Akwa Ibom'),
            (AN,'Anambra'),
            (BU,'Bauchi'),
            (BY,'Bayelsa'),
            (BN,'Benue'),
            (BO,'Borno'),
            (CR,'Cross River'),
            (DL,'Delta'),
            (EB,'Ebonyi'),
            (ED,'Edo'),
            (EK,'Ekiti'),
            (EN,'Enugu'),
            (GO,'Gombe'),
            (IM,'Imo'),
            (JI,'Jigawa'),
            (KD,'Kaduna'),
            (KN,'Kano'),
            (KT,'Katsina'),
            (KB,'Kebbi'),
            (KG,'Kogi'),
            (KW,'Kwara'),
            (LG,'Lagos'),
            (NS,'Nasarawa'),
            (NG,'Niger'),
            (OG,'Ogun'),
            (ON,'Ondo'),
            (OS,'Osun'),
            (OY,'Oyo'),
            (PL,'Plateau'),
            (RS,'Rivers'),
            (SK,'Sokoto'),
            (TR,'Taraba'),
            (YB,'Yobe'),
            (ZM,'Zamfara')

    ]



    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.IntegerField(null=True, blank=True)
    dob = models.DateField(null=True, blank=True)
    address = models.CharField(max_length=300, null=True, blank=True)
    city = models.CharField(max_length=10, null=True, blank=True)
    
    state = models.CharField(max_length=11, choices=state, default=AB, null=True, blank=False)
    
    gender = models.CharField(max_length=1, 
                              choices=gender, default=Male)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')    


    def __str__(self):
        return self.user.username
    
    #override the save method of the model
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        #open the image
        img = Image.open(self.image.path)

        #resizing the image and save to override the other one
        if img.height > 100 or img.width > 100:
            output_size = (40, 40)

            #RESIZE THE IMAGE   
            img.thumbnail(output_size)

            #SAVE IT AGAIN AND OVERRIDE THE LARGER IMAGE
            img.save(self.image.path)


    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)
            
    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.userprofile.save()


class ContactUs (models.Model):
    full_name = models.CharField("Full Name", max_length=20)
    phone_num = models.BigIntegerField()
    email = models.EmailField()
    text = models.TextField(max_length=250)



    def __str__(self):
        return self.full_name

backend/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile
from .models import ContactUs
#create your forms



class NewUserForm(UserCreationForm):
    username = forms.CharField(max_length=15, widget=forms.TextInput(attrs={'class':'form-control','placeholder':'ENTER YOUR USERNAME',}))
    email = forms.EmailField(max_length=20, widget=forms.EmailInput(attrs={'class':'form-control','placeholder':'ENTER YOUR E-MAIL',}))
    password1 = forms.CharField(max_length=10, widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'ENTER YOUR PASSWORD',}))
    password2 = forms.CharField(max_length=10, widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'CONFRIM YOUR PASSWORD',}))
   

    class Meta:
        model = User
        fields = ("username", "email", "password1","password2")
        labels = {
            'username':'.',
            'email':'',
            'password1':'.',
            'password2':'.',
        }
    '''
    def __init__(self, *args, **kwargs):
        super(NewUserForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class']='form-control'
        self.fields['password1'].widget.attrs['class']='form-control'
        self.fields['password2'].widget.attrs['class']='form-control'     

       # def save(self, commit=True):
           # User = super(NewUserForm, self).save(commit=False)
            #User.email = self.cleaned_data ['email']

            #if commit:
               # User.save()
           # return User
    '''
class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile    
        fields = ('phone', 'dob', 'address', 'city','state','gender','image',)
        
class ContactForm(forms.ModelForm):
   class Meta:
         model = ContactUs
         fields = ('full_name', 'phone_num', 'email', 'text',)

backend/views.py
from typing import Any
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from .forms import NewUserForm, UserUpdateForm, ProfileForm, ContactForm #NewRegistration
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout #login and logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm , PasswordResetForm, SetPasswordForm
import datetime
from django.core.mail import send_mail
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy


today_date = datetime.date.today()
current_year = today_date.strftime('%Y')

current_month = today_date.strftime('%B')

# Create your views here.

def home(request):
    return render(request, 'home.html', {'title':'Home','current_year':current_year})

def index(request):
    return render(request, 'index.html', {'title':'Home','current_year':current_year})

def about(request):
    return render(request, 'about.html', {'title':'About','current_year':current_year})

def inbox(request):
    return render(request, 'about.html', {'title':'About','current_year':current_year})

def settings(request):
    return render(request, 'settings.html', {'title':'settings','current_year':current_year})

def contact(request):
    if request.method == 'POST':
      
        form = ContactForm(request.POST)

        if form.is_valid():
            full_name = form.cleaned_data.get('full_name')
            phone_num = form.cleaned_data.get('phone_num')
            email =form.cleaned_data.get('email')
            text = form.cleaned_data.get('text')   
            form.save()
            messages.success(request, 'THANKS FOR THE INFO, WE WILL GET BACK TO YOU')
            send_mail(
                subject= full_name,
                message= text,
                from_email= email,
                recipient_list=['ugonjokubarthlomew@gmail.com','mccathly@gmail.com'],
                fail_silently=False,
            )
            return redirect("backend:contact")
        else:
            messages.error(request, "PLEASE FILL UP YOUR INFO")
    form = ContactForm()
    template = loader.get_template("contact.html")
    context = {
        'contact_form':form,
        'current_year': current_year,
    }
    return HttpResponse(template.render(context, request))

@login_required(login_url='login/')
def courses(request):
    return render(request, 'courses.html', {'title':'Courses','current_year':current_year})

#FOR SEARCH BAR

#creating a registration form
def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            user = form.save()
            #login(request, User)
            messages.success(request, "Registration successful.")
            
            return redirect("backend:login")
        else:
            messages.error(request, "Unsuccessful Registration. Invalid Information")
    form = NewUserForm()
    template = loader.get_template("register.html")
    context = {
        'register_form': form,
        'current_year':current_year,
    }
    return HttpResponse(template.render(context, request))

#LOGIN

def login_request(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f"You are now logged in as {username}.")
                #what you have here is app name : patter/link name
                return redirect('backend:dashboard')
            else:
                messages.error(request, "Invalid username or "  + "password.")
                return redirect('backend:login')
        else:
            messages.error(request, "Invalid username or password")
            return redirect('backend:login')
    form = AuthenticationForm()
    template = loader.get_template("login.html")
    context = {
        "login_form": form,
        'current_year':current_year,
    }
    return HttpResponse(template.render(context, request))
    
@login_required(login_url='login/')
def update(request):
    #user_id = request.User.id 
    #mydashboard = User.objects.filter(id=user_id)
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.userprofile)

        #validate the form
        if user_form.is_valid() and profile_form.is_valid():      
            user_form.save()
            profile_form.save()
            messages.success(request, 'update successful')
            return redirect('backend:dashboard')
        else:
            user_form = UserUpdateForm(request.POST, instance=request.user)
            profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.userprofile)
            messages.error(request, "please check your form")
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.userprofile)

    template = loader.get_template('update.html')
    context = {

        'user' : request.user,
        'user_form': user_form,
        'profile_form': profile_form,
        'current_year':current_year,

    }
    return HttpResponse(template.render(context, request))



@login_required(login_url='login/')
def logout_request(request):
    logout(request)
    messages.success(request, "You have successfully logged out.")
    return redirect('backend:login')

@login_required(login_url='login/')
def dashboard(request):
    return render(request, 'dashboard.html', {'title':'Dashboard','current_year':current_year ,'current_month':current_month, 'today':today_date,})




#FOR PASSWORD RESETTING OR FORGOT PASSWORD


class CustomPasswordResetView(PasswordResetView):
    success_url = '/password_reset_done'
    email_template_name = 'password/custom_password_reset_email.html'
    template_name = 'password/custom_password_reset_form.html'
    subject_template_name = 'password/custom_password_reset_subject.txt'
    from_email = 'ugonjokubarthlomew@gmail.com'
    form_class = PasswordResetForm
    token_generator = default_token_generator
    extra_context = {
        'title':'title',
        'form':form_class,
    }
    extra_email_context ={
        'domain': 'www.apache.com',
        'protocol':'http',
        'email': User.email,
        'user':User.username,
        'uid':User.pk,
        'token': token_generator,
    }
    
    def form_valid(self, form):
        opts = {
            "use_https": self.request.is_secure(),
            "token_generator": self.token_generator,
            "from_email": self.from_email,
            "email_template_name": self.email_template_name,
            "subject_template_name": self.subject_template_name,
            "request": self.request,
            "html_email_template_name": self.html_email_template_name,
            "extra_email_context": self.extra_email_context,
        }
        form.save(**opts)
        return super().form_valid(form)

    def form_invalid(self, form):
        response = super().form_valid(form)
        return response
        

class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'password/custom_password_reset_done.html'

class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'password/custom_password_reset_confirm.html'
    success_url = reverse_lazy('/password_reset_complete')
    token_generator = default_token_generator
    post_reset_login = False
    post_reset_login_backend = None
    form_class = SetPasswordForm
    extra_context = {
        'form':form_class,
        'title':'password reset'

    }
    reset_url_token = 'set-password'
    
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    

    def form_invalid(self, form):

        return super().form_invalid(form)

class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'password/custom_password_reset_complete.html'

backend/templates/base.html
<!doctype html>
<html lang="en">
  <head>
   
  </head>
  <body>
    <h1>Hello, world!</h1>
   
</html>

backend/templates/carousel.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '../static/css/home.css' %}">
<div class="carousel">
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src=" {% static '../static/images/classro.jpg' %}" class="d-block w-100" alt="a">
          </div>
          <div class="carousel-item">
            <img src=" {% static '../static/images/wire.jpg' %}" class="d-block w-100" alt="b">
          </div>
          <div class="carousel-item">
            <img src=" {% static '../static/images/teacher.jpg' %}" class="d-block w-100" alt="c">
          </div>
        </div>
      </div>
</div>

backend/templates/courses.html
{% extends 'master.html' %}

backend/templates/dashboard-carousel.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '../static/css/home.css' %}">
<div class="carousel">
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src=" {% static '../static/images/LMSgirl.jpg' %}" class="d-block w-100" alt="a">
          </div>
          <div class="carousel-item">
            <img src=" {% static '../static/images/wire.jpg' %}" class="d-block w-100" alt="b">
          </div>
          <div class="carousel-item">
            <img src=" {% static '../static/images/manandson.jpg' %}" class="d-block w-100" alt="c">
          </div>
          <div class="carousel-item">
            <img src=" {% static '../static/images/teacher.jpg' %}" class="d-block w-100" alt="c">
          </div>
          <div class="carousel-item">
            <img src=" {% static '../static/images/hausa.jpg' %}" class="d-block w-100" alt="c">
          </div>
        </div>
      </div>
</div>

backend/templates/dashboard.html
<!DOCTYPE html>

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %} 
    <title>Django {{ title }} </title>
    {% else %}
    <title>{{ title }}</title>
    {% endif %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static '/backend/static/css/dashboard.css' %}">
</head>
{% block content %}
<body style='background-color:aliceblue;'>
    {% include 'dashboard-navbar.html' %}
    {% if user.is_authenticated %}
    
    {% if messages %}
    {% for messages in messages %}
    
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{messages}} 
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

    {% if messages.tags %} 
            
    {% endif %} 
    {% endfor %}
    {% endif %}
    <br>
    <div style="background-color:green" class="d-flex align-items mb-3"> 
        <h1 class='lor'> WELCOME TO THE DASHBOARD!!!! <span style='color:red;text-transform:uppercase;'> {{user.username}} </span></h1> 
        <form class="d-flex flex-row-reverse ms-auto p-2" role="search">
            <button class="btn btn-success p-2" type="submit">Search </button>
            <input class="form-control w-75" type="search" placeholder="Type here to search. . . " aria-label="Search">
          </form>
    </div>    
    <style>
        .lor{
            text-shadow:white 3px 1px 1px;
        }
    </style> 
    <br>
        <div class='d-flex justify-content-evenly'>

        <div style='background-color:black' class='shadow col-4 w-25 p-4 bg-body rounded row '>
            <br>
            <center class='border-bottom'>
                <h1 class='chase'>CATEGORIES</h1>
            </center>
            <ul>
                <br>
                <a class='border-bottom' href="{% url 'backend:courses' %}" style='display:block; text-decoration:none;color:black;'><span class='axe'> GO TO CLASS </span> </a>
                <br>
                <a class='border-bottom' href="{% url 'backend:courses' %}" style='display:block; text-decoration:none;color:black;'><span class='axe'> NEW COURSE</span> </a>
                <br>
                <a class='border-bottom' href="{% url 'backend:courses' %}" style='display:block; text-decoration:none;color:black;'><span class='axe'> ATTENDANCE </span> </a>
                <br>
                <a class='border-bottom' href="{% url 'backend:courses' %}" style='display:block; text-decoration:none;color:black;'><span class='axe'> FREE COURSES </span> </a>
                <br>
                <a class='border-bottom' href="{% url 'backend:courses' %}" style='display:block; text-decoration:none;color:black;'><span class='axe'> PAID COURSES </span> </a>
                <br>
                <a class='border-bottom' href="{% url 'backend:courses' %}" style='display:block; text-decoration:none;color:black;'><span class='axe'> CALENDAR </span> </a>
                <br>
                <a href="{% url 'backend:courses' %}" style='display:block; text-decoration:none;color:black;'> <span class='axe'> EVENTS </span> </a>
                <br>
               
            </ul>
            <style>
                .axe:hover{
                    background-color:aliceblue;
                    color:red;
                    border-left:red ridge;
                    font-weight:bold;
                    text-indent:20px;
                }
                .chase{
                    text-shadow:1px 1px 5px green;
                }
            </style>
            <div class='float-end'>
                {% include 'dashboard-carousel.html' %}
            </div>

        </div>
        <div class='float-end w-75'>
            {% include 'dashboard-carousel.html' %}
        </div>
    </div>
    <br><br><br>
    <div class='shadow col-4 w-100 p-4 bg-body rounded'>
       
        <h1 style='border-left:red ridge'> HOT TOPICS </h1>
        <br><br><br>
        <div class='flex-container'>
            <div class='flex-item w-25'>Html</div>
            <div class='flex-item w-25'>Python</div>
            <div class='flex-item w-25'>Javascript</div>
            <div class='flex-item w-25'>Css</div>
            <div class='flex-item w-25'>Django</div>

        </div>

          
      
    </div>
    <style>
        .shadow flex_container{
            display:flex;
            align-items: center,
            flex-direction:row,
            justify-content:center
        }
    </style>

   

    {% endif %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
<br>
<footer style='background-color:black;color:white;'>SKILLUPLMS.COM (c) {{ current_month }} {{ current_year }} </footer>
{% endblock content %}

backend/templates/home.html
{% extends 'master.html' %}

{% if title %} 
<title>Django {{ title }} </title>
{% else %}
<title>{{ title }}</title>
{% endif %}
{% block content %}
{% include 'carousel.html' %} 
<br>
   <div class='div1'>
        <div class="ddiv">
            <h1>WELCOME TO SKILLUP LMS</h1>
            <h3>New User? Register here</h3>
            <button type="submit" class="btn btn-success"><a href="{% url 'backend:registration' %}">Sign up</a></button>
        </div>
    </div>
{% endblock %}
   
   

backend/templates/index.html
{% extends "master.html" %}

{% block title %} home {% endblock %}

{% block content %}
<h1 style='clolor: red'> WELCOME TO SKILLUP LMS</h1>
        <h3>New USer? Register here</h3>
        <button type="submit"><a href="{% url 'backend:registration' %}">Sign up</a></button>
            
{% endblock %}       

 

backend/templates/master.html
<!DOCTYPE html>
{% load widget_tweaks %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>   
    <link rel="stylesheet" type="text/css" href="{% static 'css/master.css' %}" >
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static '../static/css/home.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '../static/css/master.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '../static/css/register.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '../static/css/dashboard.css' %}">
</head>
<body>
     {% include 'navbar.html' %}  
     <br>
    <main>
       {% block content %} 
       
       
       {% endblock %}
    </main>
    <footer>
        <div class="A1">
        copyright (c) {{ current_year }} powered by Skillup Cohort 2, under the initiative of 3R movement
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

backend/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'backend:home' %}">SKILLUPLMS.COM</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'backend:home' %}">Home</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Menu
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'backend:login' %}">Login</a></li>
              <li><a class="dropdown-item" href="{% url 'backend:about' %}">About Us</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'backend:contact' %}">Contact Us</a></li>
              <li><a class="dropdown-item" href="{% url 'backend:courses' %}">Courses</a></li>
            </ul>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search for courses..." aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>